version: '3'
services:
  db:
    image: mongo:3.4
  backend:
    image: node:8.1
    volumes:
      - D:/OneDrive/Estudos/Docker/Udemy/node-mongo-compose/backend/:/backend
    ports:
      - 3000:3000
    command: bash -c "cd /backend && npm i && node app"
  frontend:
    image: nginx:1.13
    volumes:
      - D:/OneDrive/Estudos/Docker/Udemy/node-mongo-compose/frontend/:/usr/share/nginx/html/
    ports:
      - 80:80
